Group : Genesis

Members:

    Thulana Abeywardane (C0861333)
    
    Tomson George (C0857730)
    
    Praveen Mahaulpatha (C0860583)

# 1. Import Dependencies

In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# 2. Loading Data & EDA

In [6]:
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context



In [12]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=["age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "class"])

In [13]:
df.shape

(32561, 15)

In [14]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country   class  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [15]:
df.tail()

age      workclass  fnlwgt    education  education-num  \
32556   27        Private  257302   Assoc-acdm             12   
32557   40        Private  154374      HS-grad              9   
32558   58        Private  151910      HS-grad              9   
32559   22        Private  201490      HS-grad              9   
32560   52   Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation relationship    race      sex  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loss  hours-per-week  native-country   class  
32556             0             0              38   United-States   <=50K  
32557             0             0              40   United-States    >50K  
32558             0             0              40   United-States   <=50K  
32559             0             0              20   United-States   <=50K  
32560         15024             0              40   United-States    >50K

In [17]:
df.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [19]:
# Checking for null values
df.isnull().mean()

age               0.0
workclass         0.0
fnlwgt            0.0
education         0.0
education-num     0.0
marital-status    0.0
occupation        0.0
relationship      0.0
race              0.0
sex               0.0
capital-gain      0.0
capital-loss      0.0
hours-per-week    0.0
native-country    0.0
class             0.0
dtype: float64

In [26]:
# Encode the Label value (Dependent Variable)

In [31]:
df['class'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [32]:
df['class'] = df['class'].map(lambda x: 1 if x==' <=50K' else 0)

In [42]:
df['class'].value_counts()

1    24720
0     7841
Name: class, dtype: int64

In [43]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  class  
0          2174             0              40   United-States      1  
1             0             0              13   United-States      1  
2             0             0              40   United-States      1  
3             0             0              40   United-States      1  
4             0             0              40            Cuba      1

# 3.Classification : Numerical Features

In [44]:
df_numeric = df.select_dtypes(include=np.number)

In [45]:
df_numeric.shape

(32561, 7)

In [46]:
df_numeric.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

## 3.1 Splitting Testing and Traininig Set

In [92]:
X = df_numeric.drop('class',axis=1)
y = df_numeric['class']

In [93]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

In [94]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(24420, 6) (8141, 6) (24420,) (8141,)


## 3.2 Normalize the data for better accuracy

In [95]:
from sklearn.preprocessing import MinMaxScaler

In [96]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 3.3 Linear Regression

In [97]:
model_lr = LinearRegression()
model_lr.fit(X_train_scaled,y_train)

LinearRegression()

In [105]:
y_pred = model_lr.predict(X_test_scaled)

In [106]:
y_pred_rounded = y_pred.round()

In [107]:
y_pred_rounded

array([1., 1., 1., ..., 1., 1., 1.])

In [108]:
np.unique(y_pred_rounded)

array([-1.,  0.,  1.])

In [112]:
# Changing all -1 values to 0
y_pred_rounded = np.where(y_pred_rounded == -1, 0, y_pred_rounded)

In [113]:
np.unique(y_pred_rounded)

array([0., 1.])

In [114]:
model_lr.score(X_test_scaled,y_test)

0.23045259468412504

## 3.4 Logistic Regression

In [116]:
model_log_reg = LogisticRegression()
model_log_reg.fit(X_train_scaled,y_train)

LogisticRegression()

In [117]:
y_pred = model_log_reg.predict(X_test_scaled)

In [118]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [121]:
# Checking the score
model_log_reg.score(X_test_scaled,y_test)

0.8141505957499079

## 3.5 Decision Tree

In [123]:
model_dec_tree = DecisionTreeClassifier()
model_dec_tree.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [124]:
y_pred = model_dec_tree.predict(X_test_scaled)

In [125]:
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [126]:
# Checking the accuracy score
model_dec_tree.score(X_test_scaled,y_test)

0.7662449330549073

## 3.6 Random Forest

In [129]:
model_rand_f = RandomForestClassifier()
model_rand_f.fit(X_train_scaled,y_train)

RandomForestClassifier()

In [130]:
y_pred = model_rand_f.predict(X_train_scaled)

In [131]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [132]:
# Checking Score
model_rand_f.score(X_test_scaled,y_test)

0.8038324530156

**Note : The Logistic regression out performed other algorithms with an accuracy of 81%**

# 4.Classification : All the Features

In [134]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  class  
0          2174             0              40   United-States      1  
1             0             0              13   United-States      1  
2             0             0              40   United-States      1  
3             0             0              40   United-States      1  
4             0             0              40            Cuba      1

In [135]:
# Select Categorical Columns
df_categorical_features = df.select_dtypes(include=['object'])

In [142]:
# Categorical column names
df_categorical_features.columns

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country'],
      dtype='object')

In [144]:
# Number of unique classes of the categorical columns
df_categorical_features.nunique()

workclass          9
education         16
marital-status     7
occupation        15
relationship       6
race               5
sex                2
native-country    42
dtype: int64

In [139]:
# One hot encoding for categorical columns
df = pd.get_dummies(df, columns=df_categorical_features.columns)

In [140]:
df.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   class  workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  ...  \
0      1             0                       0                     0  ...   
1      1             0                       0                     0  ...   
2      1             0                       0                     0  ...   
3      1             0                       0                     0  ...   
4      1             0                       0                     0  ...   

   native-country_ Portugal  native-country_ Puerto-Rico  \
0                         0                            0   
1                         0                            0   
2                         0                            0   
3                         0                            0   
4                         0                            0   

   native-country_ Scotland  native-country_ South  native-country_ Taiwan  \
0                         0                      0                       0   
1                         0                      0                       0   
2                         0                      0                       0   
3                         0                      0                       0   
4                         0                      0                       0   

   native-country_ Thailand  native-country_ Trinadad&Tobago  \
0                         0                                0   
1                         0                                0   
2                         0                                0   
3                         0                                0   
4                         0                                0   

   native-country_ United-States  native-country_ Vietnam  \
0                              1                        0   
1                              1                        0   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   native-country_ Yugoslavia  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 109 columns]

## 4.1 Splitting Testing and Traininig Set

In [145]:
X = df.drop('class',axis=1)
y = df['class']

In [146]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

In [147]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(24420, 108) (8141, 108) (24420,) (8141,)


## 4.2 Normalize the data for better accuracy

In [148]:
from sklearn.preprocessing import MinMaxScaler

In [149]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 4.3 Linear Regression

In [150]:
model_lr = LinearRegression()
model_lr.fit(X_train_scaled,y_train)

LinearRegression()

In [151]:
y_pred = model_lr.predict(X_test_scaled)

In [152]:
y_pred_rounded = y_pred.round()

In [153]:
y_pred_rounded

array([1., 1., 0., ..., 1., 0., 1.])

In [154]:
np.unique(y_pred_rounded)

array([-1.,  0.,  1.])

In [155]:
# Changing all -1 values to 0
y_pred_rounded = np.where(y_pred_rounded == -1, 0, y_pred_rounded)

In [156]:
np.unique(y_pred_rounded)

array([0., 1.])

In [157]:
model_lr.score(X_test_scaled,y_test)

0.3670549684051285

## 4.4 Logistic Regression

In [158]:
model_log_reg = LogisticRegression()
model_log_reg.fit(X_train_scaled,y_train)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [159]:
y_pred = model_log_reg.predict(X_test_scaled)

In [160]:
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [161]:
# Checking the score
model_log_reg.score(X_test_scaled,y_test)

0.8571428571428571

## 4.5 Decision Tree

In [162]:
model_dec_tree = DecisionTreeClassifier()
model_dec_tree.fit(X_train_scaled,y_train)

DecisionTreeClassifier()

In [163]:
y_pred = model_dec_tree.predict(X_test_scaled)

In [164]:
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [165]:
# Checking the accuracy score
model_dec_tree.score(X_test_scaled,y_test)

0.8232403881587028

## 4.6 Random Forest

In [166]:
model_rand_f = RandomForestClassifier()
model_rand_f.fit(X_train_scaled,y_train)

RandomForestClassifier()

In [167]:
y_pred = model_rand_f.predict(X_train_scaled)

In [168]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [169]:
# Checking Score
model_rand_f.score(X_test_scaled,y_test)

0.8580027023707161

**Note : The Random Forest out performed other algorithms with an accuracy of 85%**

# 5. PCA

In [180]:
from sklearn.decomposition import PCA

In [181]:
pca = PCA(n_components = 2)

In [182]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

In [183]:
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
 
explained_variance = pca.explained_variance_ratio_

In [184]:
explained_variance

array([0.99537314, 0.00461206])

## 5.1 Linear Regression

In [185]:
model_lr = LinearRegression()
model_lr.fit(X_train,y_train)

LinearRegression()

In [186]:
y_pred = model_lr.predict(X_test)

In [187]:
y_pred_rounded = y_pred.round()

In [188]:
y_pred_rounded

array([1., 1., 1., ..., 1., 1., 1.])

In [189]:
np.unique(y_pred_rounded)

array([-1.,  0.,  1.])

In [190]:
# Changing all -1 values to 0
y_pred_rounded = np.where(y_pred_rounded == -1, 0, y_pred_rounded)

In [191]:
np.unique(y_pred_rounded)

array([0., 1.])

In [192]:
model_lr.score(X_test,y_test)

0.05126069070101069

## 5.2 Logistic Regression

In [195]:
model_log_reg = LogisticRegression()
model_log_reg.fit(X_train,y_train)

LogisticRegression()

In [196]:
y_pred = model_log_reg.predict(X_test)

In [197]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [198]:
# Checking the score
model_log_reg.score(X_test,y_test)

0.7841788478073947

## 5.3 Decision Tree

In [199]:
model_dec_tree = DecisionTreeClassifier()
model_dec_tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [200]:
y_pred = model_dec_tree.predict(X_test)

In [201]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [202]:
# Checking the accuracy score
model_dec_tree.score(X_test,y_test)

0.7302542685173812

## 5.4 Random Forest

In [203]:
model_rand_f = RandomForestClassifier()
model_rand_f.fit(X_train,y_train)

RandomForestClassifier()

In [204]:
y_pred = model_rand_f.predict(X_train)

In [205]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [206]:
# Checking Score
model_rand_f.score(X_test,y_test)

0.747942513204766

**Note : Eventhough the dimentionality was reduced significantly the best accuracy obtained through PCA was around78%. This is a a 7% loss compared to the best result we have got so far.**